package config

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

const (
	DefaultAgentVersion     = "0.1.0-dev"
	DefaultMaxFileBytes     = 2 * 1024 * 1024 // 2 MiB
	DefaultStateDirName     = "oncode-agent"
	DefaultMaxSearchResults = 200
)

// DefaultSearchExcludeDirs are skipped during workspace.search (PHASE_01).
func DefaultSearchExcludeDirs() []string {
	return []string{".git", "target", "node_modules", "dist", "build"}
}

// Config holds Local Agent runtime settings.
type Config struct {
	AgentID      string
	AgentVersion string
	StateDir     string
	MaxFileBytes int64
}

// Load returns defaults suitable for Phase 1 development.
// AgentID is generated by the caller if empty after Load.
func Load() (Config, error) {
	cfg := Config{
		AgentVersion: DefaultAgentVersion,
		MaxFileBytes: DefaultMaxFileBytes,
	}
	if v := os.Getenv("ONCODE_AGENT_VERSION"); v != "" {
		cfg.AgentVersion = v
	}
	if v := os.Getenv("ONCODE_AGENT_ID"); v != "" {
		cfg.AgentID = v
	}

	stateDir := os.Getenv("ONCODE_AGENT_STATE_DIR")
	if stateDir == "" {
		base, err := os.UserConfigDir()
		if err != nil {
			base = os.TempDir()
		}
		stateDir = filepath.Join(base, DefaultStateDirName)
	}
	abs, err := filepath.Abs(stateDir)
	if err != nil {
		return Config{}, fmt.Errorf("state dir: %w", err)
	}
	cfg.StateDir = abs

	if err := os.MkdirAll(cfg.StateDir, 0o700); err != nil {
		return Config{}, fmt.Errorf("create state dir: %w", err)
	}
	return cfg, nil
}

// PlatformOS returns the GOOS string.
func PlatformOS() string { return runtime.GOOS }

// PlatformArch returns the GOARCH string.
func PlatformArch() string { return runtime.GOARCH }
